# This workflow will install Python dependencies and run tests with a single version of Python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python3 firewall_autozoner.py -s -1 "SRC_IP" -2 "DEST_IP" -n -x "CRITICAL" -o "zoned-test-0.csv" "policy-example.csv" "rib-example.csv"
        cmp zoned-example-0.csv zoned-test-0.csv
        python3 firewall_autozoner.py -s -1 "SRC_IP" -2 "DEST_IP" -n -z 7 -x "CRITICAL" -o "zoned-test-1.csv" "policy-example.csv" "rib-example.csv"
        cmp zoned-example-1.csv zoned-test-1.csv
        python3 firewall_autozoner.py -s -1 "SRC_IP" -2 "DEST_IP" -n -z 7 -b -x "CRITICAL" -o "zoned-test-2.csv" "policy-example.csv" "rib-example.csv"
        cmp zoned-example-2.csv zoned-test-2.csv
        python3 firewall_autozoner.py -s -1 "SRC_IP" -2 "DEST_IP" -a -x "CRITICAL" -o "zoned-test-3.csv" "policy-example.csv" "rib-example.csv"
        cmp zoned-example-3.csv zoned-test-3.csv
        
